##The maximum a player can carry by default
Default-player-weight: 100

##The weight point at which the player speed will start decreasing until the Maximum-Speed-Decrease
##Must be lower than the max player weight. -1 if you don't want the speed to decrease
Speed-decrease-start: 75

##The PERCENTAGE that you want the player to be slowed down when they reach their maximum weight
##Enter a number from 0 to 100 as if it was a PERCENTAGE, don't add a % symbol
Maximum-speed-decrease: 100

##If an items weight isn't provided, it will automatically default to the Default-item-weight
Default-item-weight: 1

##Enter the Item that you want with an INTEGER for its weight
##https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html list of all items in format
Custom-weights:
  DIRT: 1
