name: PlayerWeight
version: ${project.version}
main: me.chaoticwagon.playerweight.Main
api-version: 1.17
authors: [ chaoticwagon ]
description: Adds a weight system to your minecraft server.
commands:
  getweight:
    description: returns the weight of the player targeted
  playerweight:
    description: reloads the plugin
    aliases: pw
  setitemweight:
    description: sets the weight of the item in the player hand in the config
  setmaxweight:
    description: sets the max player weight in the config